# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
MD007:
  indent: 4

# Remove line length limit - no one wants to hard wrap all their paragraphs
MD013: false

# need some html in some places!
MD033: false

# glossary.md needs to not have a header to work
MD041: false

# sometimes you want to increment headers by more than one
MD001: false
